"""user-product

Revision ID: 0080f48912fb
Revises: 643cec76bc8a
Create Date: 2024-10-26 20:47:23.420421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0080f48912fb'
down_revision: Union[str, None] = '643cec76bc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###
