"""add co2

Revision ID: 14cec08d0d99
Revises: e203704eeb84
Create Date: 2024-10-27 04:01:58.662173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cec08d0d99'
down_revision: Union[str, None] = 'e203704eeb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('co2', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('count', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('co2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'co2')
    op.drop_column('product', 'count')
    op.drop_column('product', 'co2')
    # ### end Alembic commands ###
