"""Init

Revision ID: 1ca8f4ec53fe
Revises: cf52e1d3f441
Create Date: 2024-10-26 18:57:04.193187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8f4ec53fe'
down_revision: Union[str, None] = 'cf52e1d3f441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'f')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('f', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
