"""add container and types

Revision ID: aa993adb56d7
Revises: cee43a28f7ce
Create Date: 2024-10-26 23:51:29.297718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa993adb56d7'
down_revision: Union[str, None] = 'cee43a28f7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('x', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('y', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['product_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'product_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'type_id')
    op.drop_table('container')
    op.drop_table('product_type')
    # ### end Alembic commands ###
