"""product_e-type

Revision ID: cd75b2aab8f7
Revises: c8ce18459bf8
Create Date: 2024-10-27 04:22:43.033978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd75b2aab8f7'
down_revision: Union[str, None] = 'c8ce18459bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_e', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_e', 'product_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_e', type_='foreignkey')
    op.drop_column('product_e', 'type_id')
    # ### end Alembic commands ###
