"""product status

Revision ID: cee43a28f7ce
Revises: 4b17ac445c3c
Create Date: 2024-10-26 22:03:43.251347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee43a28f7ce'
down_revision: Union[str, None] = '4b17ac445c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_dropped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_dropped')
    # ### end Alembic commands ###
